onEvent('item.tags', event => {
    event.add('the_vault:vault_ores', 'the_vault:ore_larimar')
    event.add('the_vault:vault_ores', 'the_vault:ore_benitoite')
    event.add('the_vault:vault_ores', 'the_vault:ore_alexandrite')
    event.add('the_vault:vault_ores', 'the_vault:ore_wutodie')
    event.add('the_vault:vault_ores', 'the_vault:ore_painite')
    event.add('the_vault:vault_ores', 'the_vault:ore_black_opal')
    event.add('the_vault:vault_ores', 'the_vault:ore_echo')
    event.add('the_vault:vault_ores', 'the_vault:ore_iskallium')
    event.add('the_vault:vault_ores', 'the_vault:ore_sparkletine')
    event.add('the_vault:vault_ores', 'the_vault:ore_tubium')
    event.add('the_vault:vault_ores', 'the_vault:ore_puffium')
    event.add('the_vault:vault_ores', 'the_vault:ore_ashium')
    event.add('the_vault:vault_ores', 'the_vault:ore_xenium')
    event.add('the_vault:vault_ores', 'the_vault:ore_petzanite')
    event.add('the_vault:vault_ores', 'the_vault:ore_upaline')
    event.add('the_vault:vault_ores', 'the_vault:ore_bomignite')
    event.add('the_vault:vault_ores', 'the_vault:ore_gorginite')
})