onEvent('item.tags', event => {

    //Vanilla mining compat
    event.add('forge:axes', 'the_vault:axe')
    event.add('forge:swords', 'the_vault:sword')

    event.add('the_vault:vault_ores', 'the_vault:ore_larimar')
    event.add('the_vault:vault_ores', 'the_vault:ore_benitoite')
    event.add('the_vault:vault_ores', 'the_vault:ore_alexandrite')
    event.add('the_vault:vault_ores', 'the_vault:ore_wutodie')
    event.add('the_vault:vault_ores', 'the_vault:ore_painite')
    event.add('the_vault:vault_ores', 'the_vault:ore_black_opal')
    event.add('the_vault:vault_ores', 'the_vault:ore_echo')
    event.add('the_vault:vault_ores', 'the_vault:ore_iskallium')
    event.add('the_vault:vault_ores', 'the_vault:ore_sparkletine')
    event.add('the_vault:vault_ores', 'the_vault:ore_tubium')
    event.add('the_vault:vault_ores', 'the_vault:ore_puffium')
    event.add('the_vault:vault_ores', 'the_vault:ore_ashium')
    event.add('the_vault:vault_ores', 'the_vault:ore_xenium')
    event.add('the_vault:vault_ores', 'the_vault:ore_petzanite')
    event.add('the_vault:vault_ores', 'the_vault:ore_upaline')
    event.add('the_vault:vault_ores', 'the_vault:ore_bomignite')
    event.add('the_vault:vault_ores', 'the_vault:ore_gorginite')

    //Tag unhinged scav items
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_broken_pottery')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_blue_scroll')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_goblet')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_poultice_jar')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_preserves_jar')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spice_jar')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_blue_bangle')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_pink_bangle')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_benitoite_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_wutodic_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_echoing_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_pogging_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_cursed_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_fangs')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_leg')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_webbing_spool')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_barnacle')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_blood_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_hide')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_arm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_nose')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_ear')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_brain')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_foot')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_fuse')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_tnt')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_bone_shard')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_milky_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_wishbone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_ribcage')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_milky_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_skull')

    event.add('the_vault:spawnegg', 'quark:wraith_spawn_egg')
    event.add('the_vault:spawnegg', 'quark:toretoise_spawn_egg')
    event.add('the_vault:spawnegg', 'quark:frog_spawn_egg')
    event.add('the_vault:spawnegg', 'cloudstorage:spawn_egg_badloon')
    event.add('the_vault:spawnegg', 'cloudstorage:spawn_egg_bloviator')
    event.add('the_vault:spawnegg', 'thermal:blizz_spawn_egg')
    event.add('the_vault:spawnegg', 'thermal:blitz_spawn_egg')
    event.add('the_vault:spawnegg', 'thermal:basalz_spawn_egg')
    event.add('the_vault:spawnegg', 'tropicraft:iguana_spawn_egg')

    event.add('the_vault:crystal_seals', 'the_vault:crystal_seal_spirits')
    event.add('the_vault:crystal_seals', 'the_vault:crystal_seal_unhinged')
    event.add('the_vault:crystal_seals', 'the_vault:crystal_seal_titan')
    event.add('the_vault:crystal_seals', 'the_vault:crystal_seal_enchanter')
    event.add('the_vault:crystal_seals', 'the_vault:crystal_seal_doomsayer')

    event.add('the_vault:crystal_capstones', 'woldsvaults:capstone_frenzy')
    event.add('the_vault:crystal_capstones', 'woldsvaults:capstone_prosperous')
    event.add('the_vault:crystal_capstones', 'woldsvaults:capstone_all_seeing_eye')
    event.add('the_vault:crystal_capstones', 'woldsvaults:capstone_enchanted')
    event.add('the_vault:crystal_capstones', 'woldsvaults:capstone_vendoors')
    event.add('the_vault:crystal_capstones', 'the_vault:mote_purity')
    event.add('the_vault:crystal_capstones', 'the_vault:mote_clarity')
    event.add('the_vault:crystal_capstones', 'the_vault:mote_sanctity')
})

onEvent('block.tags', event => {
    event.add('minecraft:mineable/pickaxe', 'the_vault:vault_salvager')

    event.add('minecraft:mineable/axe', 'sophisticatedstorage:treasure_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:ornate_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:wooden_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:living_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:gilded_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:hardened_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:flesh_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:enigma_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:altar_chest')

    event.add('forge:chests', 'sophisticatedstorage:treasure_chest')
    event.add('forge:chests', 'sophisticatedstorage:ornate_chest')
    event.add('forge:chests', 'sophisticatedstorage:wooden_chest')
    event.add('forge:chests', 'sophisticatedstorage:living_chest')
    event.add('forge:chests', 'sophisticatedstorage:gilded_chest')
    event.add('forge:chests', 'sophisticatedstorage:hardened_chest')
    event.add('forge:chests', 'sophisticatedstorage:flesh_chest')
    event.add('forge:chests', 'sophisticatedstorage:enigma_chest')
    event.add('forge:chests', 'sophisticatedstorage:altar_chest')
})

onEvent('tags.fluids', event => {
    event.add('woldsvaults:experience', 'create_enchantment_industry:experience')
    event.add('woldsvaults:experience', 'create_enchantment_industry:hyper_experience')
    event.add('woldsvaults:experience', 'industrialforegoing:essence')
}) 