onEvent('item.tags', event => {
    event.add('the_vault:vault_ores', 'the_vault:ore_larimar')
    event.add('the_vault:vault_ores', 'the_vault:ore_benitoite')
    event.add('the_vault:vault_ores', 'the_vault:ore_alexandrite')
    event.add('the_vault:vault_ores', 'the_vault:ore_wutodie')
    event.add('the_vault:vault_ores', 'the_vault:ore_painite')
    event.add('the_vault:vault_ores', 'the_vault:ore_black_opal')
    event.add('the_vault:vault_ores', 'the_vault:ore_echo')
    event.add('the_vault:vault_ores', 'the_vault:ore_iskallium')
    event.add('the_vault:vault_ores', 'the_vault:ore_sparkletine')
    event.add('the_vault:vault_ores', 'the_vault:ore_tubium')
    event.add('the_vault:vault_ores', 'the_vault:ore_puffium')
    event.add('the_vault:vault_ores', 'the_vault:ore_ashium')
    event.add('the_vault:vault_ores', 'the_vault:ore_xenium')
    event.add('the_vault:vault_ores', 'the_vault:ore_petzanite')
    event.add('the_vault:vault_ores', 'the_vault:ore_upaline')
    event.add('the_vault:vault_ores', 'the_vault:ore_bomignite')
    event.add('the_vault:vault_ores', 'the_vault:ore_gorginite')

    //Tag unhinged scav items
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_broken_pottery')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_blue_scroll')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_goblet')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_poultice_jar')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_preserves_jar')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spice_jar')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_blue_bangle')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_pink_bangle')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_benitoite_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_wutodic_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_echoing_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_pogging_gemstone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_cursed_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_fangs')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_leg')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_spider_webbing_spool')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_barnacle')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_drowned_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_blood_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_hide')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_arm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_nose')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_ear')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_brain')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_zombie_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_foot')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_fuse')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_tnt')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_creeper_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_bone_shard')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_milky_vial')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_wishbone')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_soul_charm')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_ribcage')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_milky_eye')
    event.add('the_vault:scavenger_item', 'the_vault:scavenger_skeleton_skull')


})

onEvent('block.tags', event => {
    event.add('minecraft:mineable/pickaxe', 'the_vault:vault_salvager')
})