onEvent('jei.hide.items', event => {
    event.hide('pneumaticcraft:jet_boots_upgrade_1')
    event.hide('pneumaticcraft:jet_boots_upgrade_2')
    event.hide('pneumaticcraft:jet_boots_upgrade_3')
    event.hide('pneumaticcraft:jet_boots_upgrade_4')
    event.hide('pneumaticcraft:jet_boots_upgrade_5')
    event.hide('pneumaticcraft:jumping_upgrade_1')
    event.hide('pneumaticcraft:jumping_upgrade_2')
    event.hide('pneumaticcraft:jumping_upgrade_3')
    event.hide('pneumaticcraft:jumping_upgrade_4')
    event.hide('pneumaticcraft:elytra_upgrade')
    event.hide('pneumaticcraft:creative_upgrade')
    event.hide('industrialforegoing:infinity_hammer')
    event.hide('industrialforegoing:infinity_launcher')
    event.hide('industrialforegoing:infinity_nuke')
    event.hide('industrialforegoing:infinity_backpack')
    event.hide('industrialforegoing:mob_duplicator')
    event.hide('industrialforegoing:mob_imprisonment_tool')
    event.hide('farmingforblockheads:green_fertilizer')
    event.hide('farmingforblockheads:red_fertilizer')
    event.hide('farmingforblockheads:yellow_fertilizer')
    event.hide('ironchests:dirt_chest')
    event.hide('ironchests:obsidian_chest')
    event.hide('ironchests:crystal_chest')
    event.hide('ironchests:obsidian_chest_upgrade')
    event.hide('ironchests:crystal_chest_upgrade')
    event.hide('sophisticatedvaultupgrades:debagnetizer')
    event.hide(/mysticalagriculture:.*_helmet/)
    event.hide(/mysticalagriculture:.*_chestplate/)
    event.hide(/mysticalagriculture:.*_leggings/)
    event.hide(/mysticalagriculture:.*_boots/)
    event.hide(/mysticalagriculture:.*_sword/)
    event.hide(/mysticalagriculture:.*_pickaxe/)
    event.hide(/mysticalagriculture:.*_shovel/)
    event.hide(/mysticalagriculture:.*_axe/)
    event.hide(/mysticalagriculture:.*_bow/)
    event.hide(/mysticalagriculture:.*_crossbow/)
    event.hide(/mysticalagriculture:.*_augment/)
    event.hide(/ae2additions:.*component.*/)
    event.hide(/ae2additions:.*disk.*/)
    event.hide(/ae2additions:.*storage.*/)
    event.hide(/ae2additions:.*cell.*/)
    event.hide(/advancedperipherals:.*_core/)
    event.hide('advancedperipherals:chunk_controller')
    event.hide('angelring:itemring')
    event.hide('angelring:energetic_angel_ring')
    event.hide('angelring:leadstone_angel_ring')
    event.hide('angelring:hardened_angel_ring')
    event.hide('angelring:reinforced_angel_ring')
    event.hide('angelring:resonant_angel_ring')
    event.hide(/davespotioneering:.*_umbrella/)
    event.hide('woldsvaults:capstone_vendoors')
    event.hide('ars_nouveau:mundane_belt')
    event.hide('ars_nouveau:belt_of_unstable_gifts')
    event.hide('ars_nouveau:belt_of_levitation')
    event.hide('ars_nouveau:wixie_charm')
    event.hide('ars_nouveau:enchanters_shield')
    //Blocks with rendering/crashing issues
    event.hide('blockcarpentry:frame_sign')
    event.hide('blockcarpentry:illusion_sign')
    event.hide(/ecologics:.*_sign/)
    event.hide(/quark:.*_sign/)
    event.hide(/tropicraft:.*_sign/)
    event.hide(/twigs:.*_sign/)
})



onEvent('jei.add.items', event => {
    let modifierTypes = ["reaping", "picking", "axing", "shovelling", "ornate_affinity", "coin_affinity", "gilded_affinity", "living_affinity", "wooden_affinity", "hammering", "hydrovoid", "rotating", "durability", "immortality", "mining_speed", "item_quantity", "item_rarity", "trap_disarming", "soulbound", "smelting", "pulverizing"];
    event.add('the_vault:shop_pedestal')

    modifierTypes.forEach(type => {
        event.add(Item.of('woldsvaults:chiseling_focus', { modifier: `the_vault:${type}` }))
    })
})
onEvent('jei.add.items', event => {
    event.add(Item.of('example:item', { test: 123 }))
})