onEvent('item.tooltip', tooltip => {
    tooltip.add('lightmanscurrency:wallet_copper', Text.green('Soulbound'))
    tooltip.add('lightmanscurrency:wallet_iron', Text.green('Soulbound'))
    tooltip.add('lightmanscurrency:wallet_gold', Text.green('Soulbound'))
    tooltip.add('lightmanscurrency:wallet_emerald', Text.green('Soulbound'))
    tooltip.add('lightmanscurrency:wallet_diamond', Text.green('Soulbound'))
    tooltip.add('lightmanscurrency:wallet_netherite', [Text.green('Soulbound')])
    tooltip.add('the_vault:crystal_seal_monolith', Text.red('Legacy Item'))
    tooltip.add('woldsvaults:waxing_augmenter', Text.red('Legacy Item'))
    tooltip.add('woldsvaults:waning_augmenter', Text.red('Legacy Item'))
    tooltip.add('madolives_vault_coin_pouch:coin_compacting_pouch', Text.red('Legacy Item'))
    tooltip.add('tropicraft:bamboo_sign', Text.red('Blacklisted Item'))
    tooltip.add('tropicraft:thatch_sign', Text.red('Blacklisted Item'))
    tooltip.add('tropicraft:mangrove_sign', Text.red('Blacklisted Item'))
    tooltip.add('tropicraft:palm_sign', Text.red('Blacklisted Item'))
    tooltip.add('tropicraft:mahogany_sign', Text.red('Blacklisted Item'))
    tooltip.add('botania:odin_ring', Text.red('Blacklisted Item'))

})