onEvent('block.tags', event => {

    event.add('minecraft:mineable/axe', 'sophisticatedstorage:treasure_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:ornate_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:wooden_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:living_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:gilded_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:hardened_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:flesh_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:enigma_chest')
    event.add('minecraft:mineable/axe', 'sophisticatedstorage:altar_chest')
    event.add('minecraft:mineable/pickaxe', 'sophisticatedstorage:gilded_strongbox')
    event.add('minecraft:mineable/pickaxe', 'sophisticatedstorage:ornate_strongbox')
    event.add('minecraft:mineable/pickaxe', 'sophisticatedstorage:living_strongbox')

    event.add('forge:chests', 'sophisticatedstorage:treasure_chest')
    event.add('forge:chests', 'sophisticatedstorage:ornate_chest')
    event.add('forge:chests', 'sophisticatedstorage:wooden_chest')
    event.add('forge:chests', 'sophisticatedstorage:living_chest')
    event.add('forge:chests', 'sophisticatedstorage:gilded_chest')
    event.add('forge:chests', 'sophisticatedstorage:hardened_chest')
    event.add('forge:chests', 'sophisticatedstorage:flesh_chest')
    event.add('forge:chests', 'sophisticatedstorage:enigma_chest')
    event.add('forge:chests', 'sophisticatedstorage:altar_chest')
    event.add('forge:chests', 'sophisticatedstorage:ornate_strongbox')
    event.add('forge:chests', 'sophisticatedstorage:living_strongbox')
    event.add('forge:chests', 'sophisticatedstorage:gilded_strongbox')
})